project_id = "bigkuptjbadkrfhgzvgj"

[functions.send-invitation]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-onboarding-webhook]
verify_jwt = false

[functions.rag-query]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false
