project_id = "bigkuptjbadkrfhgzvgj"

[functions.admin-reset-password]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-onboarding-webhook]
verify_jwt = false

[functions.rag-query]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.gemini-upload]
verify_jwt = true

[functions.gemini-query]
verify_jwt = true

[functions.send-custom-builds-webhook]
verify_jwt = false
