project_id = "bigkuptjbadkrfhgzvgj"

[functions.admin-reset-password]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-onboarding-webhook]
verify_jwt = false

[functions.rag-query]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.process-guideline]
verify_jwt = true

[functions.rag-search]
verify_jwt = true

[functions.rag-chat]
verify_jwt = true

[functions.send-custom-builds-webhook]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false
